apiVersion: apps/v1
kind: Deployment
metadata: 
  name: deploy-be
  labels: 
    app: deploy-backend

spec: 
  replicas: 3
  selector: 
    matchLabels:
      app: deploy-backend
    spec: 
      containers:
      - name: deploybe
        image: 100002/backend:one
        imagePullPolicy: Always
        ports: 
        - containerPort: 5000
